### ISSUE TITLE
aiozmq streams

### ISSUE THREAD

**Issue by asvetlov** [takluyver/Zantedeschia#1]
Just for your information.

I've released aiozmq 0.6 with streams API: http://aiozmq.readthedocs.org/en/0.6/stream.html

It looks like missing part of aiozmq that inspired Zantedeschia project: wrapper for zmq sockets without the need for implementing protocol class.

**Comment by takluyver** [comment]
Thanks for letting me know! That was a bit part of my frustration when I tried to use aiozmq.

I confess the whole transports & protocols part of the API confuses me. I appreciate that aiozmq probably handles things more rigorously than Zantedeschia, but it still seems like there's a lot of extra moving pieces to implement 'streams' on top of transports and protocols versus implementing a similar interface straight on the event loop, as I have done.

I noticed that you're also using the ZMQ edge-triggered FDs when the special ZmqEventLoop is not in use. Min was sceptical that this could work, and was working on a ZMQ Selector that could be plugged into select-like asyncio event loops. Have you seen any problems with the FD approach? I am a bit concerned that if every library built on asyncio requires its own event loop, the idea of interoperable async code is lost.

**Comment by takluyver** [comment]
PS if you added streams because of my remarks, my next suggestion would be to split the rpc part out as a separate package. ;-) I think there's something about ZMQ that makes people want to write RPC frameworks - I [did that](https://github.com/takluyver/zerorpc) briefly when I first learned about it.

**Comment by asvetlov** [comment]
aiozmq streams has flow control feature. That sometimes may be important. Performance is still very close to transport/protocol solution.

Yes, I've switched to using of edge triggered FD. The main reason is: new code can interoperate with any event loop (Qt, libuv or GLib for example). 

ET FDs are tricky, especially in 0ZMQ. I've asked ZeroMQ committer to review my code -- and hi found a couple errors in dark corners. Now, I hope, everything is stable.

No, I have started to work on stream API in summer but the branch was inactive half year -- nobody asked me for the feature. Anyway I've finished and merged it this week.

I don't want to drop aiozmq.rpc -- the ship is sailed. aiozmq.rpc is optional, users may not use it if they are don't need/like RPC.

**Comment by takluyver** [comment]
What exactly does flow control mean for ZMQ?

As I understand it, ZMQ already implements flow control internally - if messages are being sent faster than the receiver can handle them, ZMQ will queue them first on the recipient up to RCVHWM, and then on the sender up to SNDHWM. After that, trying to send another message will block (or fail if you use DONTWAIT).

Of course, there's a potential problem if an async message has another queue of messages ready to send, as Zantedeschia does. But Zantedeschia's send methods return a future which is not completed until the message has been 'sent' (i.e. passed to ZMQ's internal queue). So I believe that an application which does `yield from asynczmqsocket.send(...)` should be getting flow control - in that the code should not be able to generate messages faster than they can be sent.

**Comment by asvetlov** [comment]
You've answered on your own question.
0MQ has internal tools to manage flow control -- as TCP sockets has the similar in some kind.
But if you introduce own queue for outgoing data -- you need flow control for that. I've added flow control to aiozmq streams following standard asyncio TCP streams design.
Sure, most often user don't need flow control feature at all -- but when he really need that the feature cannot be added on top of existing infrastructure. Thus I've pushed flow control into transport and stream.

**Comment by takluyver** [comment]
OK, but if I correctly understood what flow control means, I have implemented it without the transport/protocol APIs, and it's simpler*. So I'm still not sure what using the transport/protocol bits gets you in this case.

(\* Of course, there might be bugs in the details of what I've done - I haven't yet tested the flow control - but unless I'm missing something big the transport/protocol API is not required for flow control.)

**Comment by asvetlov** [comment]
If you don't need sophisticated flow control -- just don't use/write it. The code without flow control is much simpler, sure.

BTW, mandatory call_soon in `.send_multipart()` makes significant performance degradation -- usually ZMQ message may be sent immediately.
